### PR TITLE
Add unit tests for entities.AccountProfileDataBean

### PR DESCRIPTION
**Pull request by JohnLBergqvist**
Hi,

I've analysed your code base and noticed that `org.apache.geronimo.daytrader.javaee6.entities.AccountProfileDataBean` in the `daytrader-entities` module is not fully tested.

I've written some tests that cover the entireity of this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

### CODE REVIEW

**Comment by dhvines** [comment]
Hey John. Thanks. I’ll take a look at it and let you know. Give me a week or two but am definitely interested, will review, and get back to you. Thanks again,

— Don
________________________________

**Comment by JohnLBergqvist** [comment]
Thanks! I've since submitted a further 2 PRs covering other classes in the same module

**Comment by JohnLBergqvist** [comment]
@dhvines

Hi Don, 

Have you had a chance to look at my PRs?

Best Regards,

John

**Comment by dhvines** [comment]
Yes. I liked at it some more. It looks like you are looking to sell me a license. Is that right or am I missing something?

________________________________

**Comment by JohnLBergqvist** [comment]
@dhvines 
No, i'm just looking for feedback on the tests. If you're happy with them and willing to merge them, there's no obligation to purchase a license. Here's an FAQ page: https://www.diffblue.com/opensource

**Comment by dhvines** [comment]
Ok. I looked at the link. If I merge them then won’t I need your tool to compile
or at least the libraries to compile the unit tests?
________________________________

**Comment by JohnLBergqvist** [comment]
@dhvines Nope, these will compile & run straight out of the box :)

**Pull request closed without merging**
